In [2]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import scipy
from sklearn import svm,metrics
import pandas

def train_svm(feat,label):
    model = svm.SVC(kernel='linear')
    model.fit(feat,label)
    return model
    
def test_classifier(ftest,classifier):
    return classifier.predict(ftest)


opts = {'rdir': './data/frames/',
        'refSize' : [80,80,3]}

ftrain = None
ltrain = None

# read the data
filename ='./data/armcurltrain.csv'
#points = np.loadtxt(filename, delimiter=',')

data1 = pandas.read_csv(filename)

x1=data1.loc[:,'Image']
y1=data1.loc[:,'Exercise']
m = len(y1)

for i in range(m):
    dirname = opts['rdir']+x1[i]
    if(not(dirname.endswith('.jpg'))):
        dirname = dirname+'.jpg'
    # read Image
    try:
        img = np.asarray(Image.open(dirname))
        img = scipy.misc.imresize(img,(opts['refSize']))
        #if i==1:
         #   imgplot = plt.imshow(img)
          #  plt.show()        
        # collapse into vector
        feat = np.reshape(img,(1,np.prod(opts['refSize'])))
        # append to dataset
        if ftrain is None:
            ftrain = feat
            ltrain = y1[i]
        else:
            ftrain = np.vstack((ftrain,feat))
            ltrain = np.hstack((ltrain,y1[i]))
    except FileNotFoundError:
        print(dirname)     

filename ='./data/lungetrain.csv'
#points = np.loadtxt(filename, delimiter=',')

data1 = pandas.read_csv(filename)

x1=data1.loc[:,'Image']
y1=data1.loc[:,'Exercise']
m = len(y1)

for i in range(m):
    dirname = opts['rdir']+x1[i]
    if(not(dirname.endswith('.jpg'))):
        dirname = dirname+'.jpg'
    # read Image
    try:
        img = np.asarray(Image.open(dirname))
        img = scipy.misc.imresize(img,(opts['refSize']))
        #if i==1:
         #   imgplot = plt.imshow(img)
          #  plt.show()        
        # collapse into vector
        feat = np.reshape(img,(1,np.prod(opts['refSize'])))
        # append to dataset
        if ftrain is None:
            ftrain = feat
            ltrain = y1[i]
        else:
            ftrain = np.vstack((ftrain,feat))
            ltrain = np.hstack((ltrain,y1[i]))
    except FileNotFoundError:
        print(dirname)     

filename ='./data/pushuptrain.csv'
#points = np.loadtxt(filename, delimiter=',')

data1 = pandas.read_csv(filename)

x1=data1.loc[:,'Image']
y1=data1.loc[:,'Exercise']
m = len(y1)

for i in range(m):
    dirname = opts['rdir']+x1[i]
    if(not(dirname.endswith('.jpg'))):
        dirname = dirname+'.jpg'
    # read Image
    try:
        img = np.asarray(Image.open(dirname))
        img = scipy.misc.imresize(img,(opts['refSize']))
        #if i==1:
         #   imgplot = plt.imshow(img)
          #  plt.show()        
        # collapse into vector
        feat = np.reshape(img,(1,np.prod(opts['refSize'])))
        # append to dataset
        if ftrain is None:
            ftrain = feat
            ltrain = y1[i]
        else:
            ftrain = np.vstack((ftrain,feat))
            ltrain = np.hstack((ltrain,y1[i]))
    except FileNotFoundError:
        print(dirname)     

filename ='./data/squattrain.csv'
#points = np.loadtxt(filename, delimiter=',')

data1 = pandas.read_csv(filename)

x1=data1.loc[:,'Image']
y1=data1.loc[:,'Exercise']
m = len(y1)

for i in range(m):
    dirname = opts['rdir']+x1[i]
    if(not(dirname.endswith('.jpg'))):
        dirname = dirname+'.jpg'
    # read Image
    try:
        img = np.asarray(Image.open(dirname))
        img = scipy.misc.imresize(img,(opts['refSize']))
        #if i==1:
         #   imgplot = plt.imshow(img)
          #  plt.show()        
        # collapse into vector
        feat = np.reshape(img,(1,np.prod(opts['refSize'])))
        # append to dataset
        if ftrain is None:
            ftrain = feat
            ltrain = y1[i]
        else:
            ftrain = np.vstack((ftrain,feat))
            ltrain = np.hstack((ltrain,y1[i]))
    except FileNotFoundError:
        print(dirname)     
        
ftest = None
ltest = None

# read the data
filename ='./data/armcurltest.csv'
#points = np.loadtxt(filename, delimiter=',')

data1 = pandas.read_csv(filename)

x1=data1.loc[:,'Image']
y1=data1.loc[:,'Exercise']
m = len(y1)

for i in range(m):
    dirname = opts['rdir']+x1[i]
    if(not(dirname.endswith('.jpg'))):
        dirname = dirname+'.jpg'
    # read Image
    try:
        img = np.asarray(Image.open(dirname))
        img = scipy.misc.imresize(img,(opts['refSize']))
        #if i==1:
         #   imgplot = plt.imshow(img)
          #  plt.show()        
        # collapse into vector
        feat = np.reshape(img,(1,np.prod(opts['refSize'])))
        # append to dataset
        if ftest is None:
            ftest = feat
            ltest = y1[i]
        else:
            ftest = np.vstack((ftest,feat))
            ltest = np.hstack((ltest,y1[i]))
    except FileNotFoundError:
        print(dirname)   

# read the data
filename ='./data/lungetest.csv'
#points = np.loadtxt(filename, delimiter=',')

data1 = pandas.read_csv(filename)

x1=data1.loc[:,'Image']
y1=data1.loc[:,'Exercise']
m = len(y1)

for i in range(m):
    dirname = opts['rdir']+x1[i]
    if(not(dirname.endswith('.jpg'))):
        dirname = dirname+'.jpg'
    # read Image
    try:
        img = np.asarray(Image.open(dirname))
        img = scipy.misc.imresize(img,(opts['refSize']))
        #if i==1:
         #   imgplot = plt.imshow(img)
          #  plt.show()        
        # collapse into vector
        feat = np.reshape(img,(1,np.prod(opts['refSize'])))
        # append to dataset
        if ftest is None:
            ftest = feat
            ltest = y1[i]
        else:
            ftest = np.vstack((ftest,feat))
            ltest = np.hstack((ltest,y1[i]))
    except FileNotFoundError:
        print(dirname)   

# read the data
filename ='./data/pushuptest.csv'
#points = np.loadtxt(filename, delimiter=',')

data1 = pandas.read_csv(filename)

x1=data1.loc[:,'Image']
y1=data1.loc[:,'Exercise']
m = len(y1)

for i in range(m):
    dirname = opts['rdir']+x1[i]
    if(not(dirname.endswith('.jpg'))):
        dirname = dirname+'.jpg'
    # read Image
    try:
        img = np.asarray(Image.open(dirname))
        img = scipy.misc.imresize(img,(opts['refSize']))
       # if i==1:
        #    imgplot = plt.imshow(img)
         #   plt.show()        
        # collapse into vector
        feat = np.reshape(img,(1,np.prod(opts['refSize'])))
        # append to dataset
        if ftest is None:
            ftest = feat
            ltest = y1[i]
        else:
            ftest = np.vstack((ftest,feat))
            ltest = np.hstack((ltest,y1[i]))
    except FileNotFoundError:
        print(dirname)   

# read the data
filename ='./data/squattest.csv'
#points = np.loadtxt(filename, delimiter=',')

data1 = pandas.read_csv(filename)

x1=data1.loc[:,'Image']
y1=data1.loc[:,'Exercise']
m = len(y1)

for i in range(m):
    dirname = opts['rdir']+x1[i]
    if(not(dirname.endswith('.jpg'))):
        dirname = dirname+'.jpg'
    # read Image
    try:
        img = np.asarray(Image.open(dirname))
        img = scipy.misc.imresize(img,(opts['refSize']))
        #if i==1:
           # imgplot = plt.imshow(img)
          #  plt.show()        
        # collapse into vector
        feat = np.reshape(img,(1,np.prod(opts['refSize'])))
        # append to dataset
        if ftest is None:
            ftest = feat
            ltest = y1[i]
        else:
            ftest = np.vstack((ftest,feat))
            ltest = np.hstack((ltest,y1[i]))
    except FileNotFoundError:
        print('Missing file : {}'.format(dirname)) 

classifier_svm = train_svm(ftrain, ltrain)
predicted = test_classifier(ftest, classifier_svm)
print(metrics.confusion_matrix(ltest,predicted))



e:\mlabs\python\lib\site-packages\ipykernel_launcher.py:40: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
e:\mlabs\python\lib\site-packages\ipykernel_launcher.py:72: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
e:\mlabs\python\lib\site-packages\ipykernel_launcher.py:104: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
e:\mlabs\python\lib\site-packages\ipykernel_launcher.py:136: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
e:\mlabs\python\lib\site-packages\ipykernel_launcher.py:172: DeprecationWarning: `imresize` is deprecated!
`imresize` is d

[[149   0   0   0]
 [  0 126   0   0]
 [  0   0  62   0]
 [  0   0   0  92]]
