In [6]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import scipy
from sklearn import svm,metrics
import pandas
import cv2
import pickle

def train_svm(feat,label):
    model = svm.SVC(kernel='linear',C=1)
    model.fit(feat,label)
    return model
    
def test_classifier(ftest,classifier):
    return classifier.predict(ftest)


opts = {'rdir': './data/frames/',
        'refSize' : [80,80,3]}

ftrain = None
ltrain = None
ftest = None
ltest = None

# read the data
filename ='./data/annotateds11.csv'
#points = np.loadtxt(filename, delimiter=',')

data1 = pandas.read_csv(filename)

x1=data1.loc[:,'Image']
y1=data1.loc[:,'Exercise']
m = len(y1)
print(m)
for i in range(m):
    dirname = opts['rdir']+x1[i]
    if(not(dirname.endswith('.jpg'))):
        dirname = dirname+'.jpg'
    # read Image
    try:
        img = np.asarray(Image.open(dirname))
        img = scipy.misc.imresize(img,(opts['refSize']))
        #if i==1:
         #   imgplot = plt.imshow(img)
          #  plt.show()        
        # collapse into vector
        feat = np.reshape(img,(1,np.prod(opts['refSize'])))
        if y1[i]=='armcurl':
            # append to dataset
            if ftrain is None:
                ftrain = feat
                ltrain = 1
            else:
                ftrain = np.vstack((ftrain,feat))
                ltrain = np.hstack((ltrain,1))
        if y1[i]=='squat':
            # append to dataset
            if ftrain is None:
                ftrain = feat
                ltrain = 2
            else:
                ftrain = np.vstack((ftrain,feat))
                ltrain = np.hstack((ltrain,2))
        if y1[i]=='pushup':
            # append to dataset
            if ftrain is None:
                ftrain = feat
                ltrain = 3
            else:
                ftrain = np.vstack((ftrain,feat))
                ltrain = np.hstack((ltrain,3)) 
        if y1[i]=='lunge':
            # append to dataset
            if ftrain is None:
                ftrain = feat
                ltrain = 4
            else:
                ftrain = np.vstack((ftrain,feat))
                ltrain = np.hstack((ltrain,4))
        if y1[i]=='backgrounda':
            # append to dataset
            if ftrain is None:
                ftrain = feat
                ltrain = 5
            else:
                ftrain = np.vstack((ftrain,feat))
                ltrain = np.hstack((ltrain,5))
        if y1[i]=='backgrounds':
            # append to dataset
            if ftrain is None:
                ftrain = feat
                ltrain = 5
            else:
                ftrain = np.vstack((ftrain,feat))
                ltrain = np.hstack((ltrain,5)) 
        if y1[i]=='backgroundp':
            # append to dataset
            if ftrain is None:
                ftrain = feat
                ltrain = 5
            else:
                ftrain = np.vstack((ftrain,feat))
                ltrain = np.hstack((ltrain,5))
        if y1[i]=='backgroundl':
            # append to dataset
            if ftrain is None:
                ftrain = feat
                ltrain = 5
            else:
                ftrain = np.vstack((ftrain,feat))
                ltrain = np.hstack((ltrain,5))                
    except FileNotFoundError:
        print(dirname)     
# read the data
filename ='./data/annotateds12.csv'
#points = np.loadtxt(filename, delimiter=',')

data1 = pandas.read_csv(filename)

x1=data1.loc[:,'Image']
y1=data1.loc[:,'Exercise']
m = len(y1)
print(m)
for i in range(m):
    dirname = opts['rdir']+x1[i]
    if(not(dirname.endswith('.jpg'))):
        dirname = dirname+'.jpg'
    # read Image
    try:
        img = np.asarray(Image.open(dirname))
        img = scipy.misc.imresize(img,(opts['refSize']))
        #if i==1:
         #   imgplot = plt.imshow(img)
          #  plt.show()        
        # collapse into vector
        feat = np.reshape(img,(1,np.prod(opts['refSize'])))
        if y1[i]=='armcurl':
            # append to dataset
            if ftest is None:
                ftest = feat
                ltest = 1
            else:
                ftest = np.vstack((ftest,feat))
                ltest = np.hstack((ltest,1))
        if y1[i]=='squat':
            # append to dataset
            if ftest is None:
                ftest = feat
                ltest = 2
            else:
                ftest = np.vstack((ftest,feat))
                ltest = np.hstack((ltest,2))
        if y1[i]=='pushup':
            # append to dataset
            if ftest is None:
                ftest = feat
                ltest = 3
            else:
                ftest = np.vstack((ftest,feat))
                ltest = np.hstack((ltest,3)) 
        if y1[i]=='lunge':
            # append to dataset
            if ftest is None:
                ftest = feat
                ltest = 4
            else:
                ftest = np.vstack((ftest,feat))
                ltest = np.hstack((ltest,4))
        if y1[i]=='backgrounda':
            # append to dataset
            if ftest is None:
                ftest = feat
                ltest = 5
            else:
                ftest = np.vstack((ftest,feat))
                ltest = np.hstack((ltest,5))
        if y1[i]=='backgrounds':
            # append to dataset
            if ftest is None:
                ftest = feat
                ltest = 5
            else:
                ftest = np.vstack((ftest,feat))
                ltest = np.hstack((ltest,5)) 
        if y1[i]=='backgroundp':
            # append to dataset
            if ftest is None:
                ftest = feat
                ltest = 5
            else:
                ftest = np.vstack((ftest,feat))
                ltest = np.hstack((ltest,5))
        if y1[i]=='backgroundl':
            # append to dataset
            if ftest is None:
                ftest = feat
                ltest = 5
            else:
                ftest = np.vstack((ftest,feat))
                ltest = np.hstack((ltest,5))                
    except FileNotFoundError:
        print(dirname)     


print(ftrain.shape)
print(ftest.shape)

classifier_svm = train_svm(ftrain, ltrain)
#with open('classifier_svmtemp.pkl', 'rb') as fid:
#    classifier_svm = pickle.load(fid) 

#with open('classifier.pkl', 'wb') as fid:
#    pickle.dump(classifier_svm, fid) 
    
predicted = test_classifier(ftest, classifier_svm)

print(metrics.confusion_matrix(ltest,predicted))

pu = Image.open("./data/pushup.png")
bg = Image.open("./data/background.png")
sq = Image.open("./data/squat.png")
lu = Image.open("./data/lunge.png")
ac = Image.open("./data/armcurl.png")

cap = cv2.VideoCapture('./data/1.mp4')

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret==1:  
        frame = frame[: : -1]
        frame = frame.transpose(1,0,2)        
        img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)        
        img = scipy.misc.imresize(img,(opts['refSize']))
        feat = np.reshape(img,(1,np.prod(opts['refSize'])))
        l = classifier_svm.predict(feat)
        if l==1:
            foreground = ac
        else:
            if l==2:
                foreground = sq
            else:
                if l==3:
                    foreground = pu 
                else:
                    if l==4:
                        foreground = lu
                    else:
                        if l==5:
                            foreground = bg
            
        frame=frame/255
        frame = Image.fromarray(np.uint8((frame)*255))      
        frame.paste(foreground, (0, 0), foreground)
        frame = np.asarray(frame)        
        cv2.imshow('frame',frame)
    if ret==0:
        break
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()



1287


e:\mlabs\python\lib\site-packages\ipykernel_launcher.py:44: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


429


e:\mlabs\python\lib\site-packages\ipykernel_launcher.py:133: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


(1287, 19200)
(429, 19200)
[[ 73   0   0   0   5]
 [  0  44   0   0   5]
 [  0   0  43   0   0]
 [  0   0   0  64   6]
 [  4   1   0   8 176]]


e:\mlabs\python\lib\site-packages\ipykernel_launcher.py:235: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
